
data class Country(
    val code:String,
    val name:String
)
object Countrylist {
    val values = listOf(
        Country("", "All Countries"),
        Country("AE", "Arab Emirates"),
        Country("AF", "Afghanistan"),
        Country("AL", "Albania"),
        Country("AM", "Armenia"),
        Country("AR", "Argentina"),
        Country("AT", "Austria"),
        Country("AU", "Australia"),
        Country("AZ", "Azerbaijan"),
        Country("BA", "Bosnia and Herzegovina"),
        Country("BD", "Bangladesh"),
        Country("BE", "Belgium"),
        Country("BF", "Burkina Faso"),
        Country("BG", "Bulgaria"),
        Country("BI", "Burundi"),
        Country("BO", "Bolivia"),
        Country("BR", "Brazil"),
        Country("BY", "Belarus"),
        Country("CA", "Canada"),
        Country("CD", "Congo"),
        Country("CH", "Switzerland"),
        Country("CL", "Chile"),
        Country("CN", "China"),
        Country("CO", "Colombia"),
        Country("CR", "Costa Rica"),
        Country("CY", "Cyprus"),
        Country("CZ", "Czechia"),
        Country("DE", "Germany"),
        Country("DK", "Denmark"),
        Country("DO", "Dominican Republic"),
        Country("EC", "Ecuador"),
        Country("EE", "Estonia"),
        Country("EG", "Egypt"),
        Country("ES", "Spain"),
        Country("FI", "Finland"),
        Country("FR", "France"),
        Country("GB", "United Kingdom"),
        Country("GE", "Georgia"),
        Country("GH", "Ghana"),
        Country("GP", "Guadeloupe"),
        Country("GR", "Greece"),
        Country("GT", "Guatemala"),
        Country("HK", "Hong Kong"),
        Country("HN", "Honduras"),
        Country("HR", "Croatia"),
        Country("HT", "Haiti"),
        Country("HU", "Hungary"),
        Country("ID", "Indonesia"),
        Country("IE", "Ireland"),
        Country("IN", "India"),
        Country("IQ", "Iraq"),
        Country("IR", "Iran"),
        Country("IT", "Italy"),
        Country("JP", "Japan"),
        Country("KE", "Kenya"),
        Country("KG", "Kyrgyzstan"),
        Country("KH", "Cambodia"),
        Country("KR", "Korea"),
        Country("KZ", "Kazakhstan"),
        Country("LB", "Lebanon"),
        Country("LT", "Lithuania"),
        Country("LV", "Latvia"),
        Country("LY", "Libya"),
        Country("MD", "Moldova"),
        Country("MK", "North Macedonia"),
        Country("MM", "Myanmar"),
        Country("MN", "Mongolia"),
        Country("MW", "Malawi"),
        Country("MX", "Mexico"),
        Country("MY", "Malaysia"),
        Country("MZ", "Mozambique"),
        Country("NA", "Namibia"),
        Country("NG", "Nigeria"),
        Country("NL", "Netherlands"),
        Country("NO", "Norway"),
        Country("NP", "Nepal"),
        Country("NZ", "New Zealand"),
        Country("PA", "Panama"),
        Country("PE", "Peru"),
        Country("PH", "Philippines"),
        Country("PK", "Pakistan"),
        Country("PL", "Poland"),
        Country("PS", "Palestine"),
        Country("PT", "Portugal"),
        Country("PY", "Paraguay"),
        Country("RO", "Romania"),
        Country("RS", "Serbia"),
        Country("RU", "Russia"),
        Country("SC", "Seychelles"),
        Country("SE", "Sweden"),
        Country("SG", "Singapore"),
        Country("SI", "Slovenia"),
        Country("SK", "Slovakia"),
        Country("SN", "Senegal"),
        Country("SO", "Somalia"),
        Country("SS", "South Sudan"),
        Country("TH", "Thailand"),
        Country("TJ", "Tajikistan"),
        Country("TR", "Turkey"),
        Country("TW", "Taiwan, Province of China"),
        Country("TZ", "Tanzania"),
        Country("UA", "Ukraine"),
        Country("US", "United States"),
        Country("UY", "Uruguay"),
        Country("UZ", "Uzbekistan"),
        Country("VE", "Venezuela"),
        Country("VN", "Viet Nam"),
        Country("XK", "Kosovo"),
        Country("ZA", "South Africa"),
        Country("ZM", "Zambia"),
        Country("ZW", "Zimbabwe")
    )
}
